blank_issues_enabled: false
contact_links:
    - name: 🗨 Discussions
      url: https://github.com/dannycreations/york/discussions
      about: Got something you think should change or be added? Search for or start a new discussion!
